version: "3.8"

services:
  app:
    build: .
    restart: always
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "80:3000"
    restart: always
